// <auto-generated />
using System;
using CheckSeparatorMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CheckSeparatorMVC.Migrations
{
    [DbContext(typeof(CheckSeparatorMvcContext))]
    [Migration("20200805160212_addIdFieldToProductsAndUser")]
    partial class addIdFieldToProductsAndUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CheckSeparatorMVC.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("ProductsAndUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductsAndUserId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("CheckSeparatorMVC.Models.ProductsAndUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("productAndUsers");
                });

            modelBuilder.Entity("CheckSeparatorMVC.Models.Product", b =>
                {
                    b.HasOne("CheckSeparatorMVC.Models.ProductsAndUser", null)
                        .WithMany("Products")
                        .HasForeignKey("ProductsAndUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
